### ISSUE TITLE
We need a block explorer, it should also tell us the status of existing nodes.

### ISSUE THREAD

**Issue by stefek99** [aeternity/testnet#27]
> It looks like there are so many people on the testnet that it is slowing down.

When speed, efficiency and scalability are your main selling point you cannot run vapourware...

**Comment by zack-bitcoin** [comment]
Enough with the spam. These issues are for people who want to contribute.

**Comment by stefek99** [comment]
See jQuery: https://github.com/jquery/jquery/issues

![image](https://cloud.githubusercontent.com/assets/249703/24902641/b41235b4-1ea2-11e7-90bd-b741cf8ce666.png)

And Angular: https://github.com/angular/angular.js/labels/PRs%20plz%21

![image](https://cloud.githubusercontent.com/assets/249703/24902687/da9ccc3a-1ea2-11e7-8422-b7c43b0ff183.png)

I also suggested created public Trello board so that new people can see what help is required.

---

https://en.wikipedia.org/wiki/Spamming

> Electronic spamming is the use of electronic messaging systems to send an unsolicited message (spam), especially advertising, as well as sending messages repeatedly on the same site.

Until recently I thought that my error reports have some merit :(

**Comment by zack-bitcoin** [comment]
labels looks like a good way of organizing.
I already have so many tabs open to deal with the aeternity community.

Ah, now that I read the title, I realize that this was not spam.
Before I had only read the text.

**Comment by Leonyxtested** [comment]
Creo que tiene razon @stefek99 ,un tablon publico donde se muestre lo que se necesita estaria bien,y otra parte para los reportes de error,te lo seguimos mandando a tu correo?

**Comment by stefek99** [comment]
Sending bug reports to @zack-bitcoin does not scale, that is why there are Github issues.

In general - you should be more focussed on coding and development - less chit-chat on Reddit, Telegram, Slack...

Weekly dev call hangout - YES, 24/7 lurking on social media - NO.

_(I know you hate me by now)_

**Comment by GroundedSage** [comment]
I love this project. However two things concern me:

**1.** The lack of developers working on this.

> In general - you should be more focussed on coding and development - less chit-chat on Reddit, Telegram, Slack...

> Weekly dev call hangout - YES, 24/7 lurking on social media - NO.

I agree with this. Focus should be on delivery and let the software speak for itself. If you host weekly dev call hangouts you can let the more involved community help with answering general questions. This scales. Having the only developer doing community management is not good.

**2.** How quickly @zack-bitcoin shut down @stefek99 who appears to be a very active contributor from what I have seen. Vapourware may be a very jarring term but upon looking it up. He has got a point with his comments. 
_software or hardware that has been advertised but is not yet available to buy, either because it is only a concept or because it is still being written or designed._


There is already a lot of talk about Aeternity being a scam or vapourware. Heck I have even raised queries about the legitimacy of this project on the erlang subreddit. I believe in it purely because of the ideas and choice of technology. This needs a strong developer community and a welcoming one at that. Perhaps finding ways that people in the Elixir community can contribute would be good. They are essentially number 1 when it comes to having a welcoming developer community.

**Comment by zack-bitcoin** [comment]
Issue is getting off-topic. I will close this one and re-create it.
