### ISSUE TITLE
{{badmatch,false},  [{pow,above_min,3,[{file,"src/pow.erl"},{line,9}]},

### ISSUE THREAD

**Issue by adrelanos** [aeternity/testnet#41]
```
user@host:~/testnet$ sh start.sh 
From https://github.com/aeternity/testnet
 * branch            master     -> FETCH_HEAD
Already up-to-date.
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
==> pink_hash (get-deps)
==> dump (get-deps)
==> trie (get-deps)
==> chalang (get-deps)
==> jiffy (get-deps)
==> cowlib (get-deps)
==> ranch (get-deps)
==> cowboy (get-deps)
==> testnet (get-deps)
==> pink_hash (compile)
==> dump (compile)
==> trie (compile)
==> chalang (compile)
==> jiffy (compile)
==> cowlib (compile)
==> ranch (compile)
==> cowboy (compile)
==> testnet (compile)
Erlang/OTP 19 [erts-8.2.1] [source] [64-bit] [smp:2:2] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V8.2.1  (abort with ^G)
1> start keys
start toptx pool started
start server
easy:sync().
<0.339.0>
syncing with peercheck top2> 
=ERROR REPORT==== 15-Apr-2017::09:43:22 ===
Error in process <0.341.0> with exit value:
{{badmatch,false},
 [{pow,above_min,3,[{file,"src/pow.erl"},{line,9}]},
  {block,check1,1,[{file,"src/consensus/tree/block.erl"},{line,196}]},
  {download_blocks,trade_blocks,4,
                   [{file,"src/consensus/download_blocks.erl"},{line,74}]},
  {download_blocks,'-sync/3-fun-0-',5,
                   [{file,"src/consensus/download_blocks.erl"},{line,44}]}]}
```

**Comment by Zwilla** [comment]
/testnet/deps/pink_hash/src/pow.erl
Line 9: true = check_pow(P, HashSize),

badmatch,false

I don’t know if this is an error I think the value here is just lower than the difficulty

**Comment by sjamayee** [comment]
I think that you have to reinstall testnet from scratch!

One of the core libraries has been updated. If you want to use the testnet, you need to completely re-install from github.
I did a reinstall and that fixed this error.

The core library update is excluded from the auto update (git pull) in the start/script.

**Comment by zack-bitcoin** [comment]
@sjamayee is exactly right. the way SHA256 is computed was slightly changed so that the blockchain would be more compatible with bitcoin and ethereum, and all the javascript libraries for bitcoin and ethereum. 
@Zwilla is also right. That is the line that is failing. Since the hash is computed differently, it looks like the block doesn't have enough proof of work to be valid.

So as sjamayee said, the way to fix this is to completely reinstall from github.
(alternatively you can delete the /deps/pink_hash folder, and then start normally. If you are on limited internet this is preferable because you don't download as much this way)

Thank you both for being so interested in Aeternity.
