### ISSUE TITLE
Windows .exe

### ISSUE THREAD

**Issue by zack-bitcoin** [aeternity/testnet#5]
We need a script that converts the source code into a stand along executable file to run on windows computers.

**Comment by stefek99** [comment]
I know the code is written in Erlang so it is not likely to work, providing link as reference / inspiration: https://electron.atom.io/

**Comment by zack-bitcoin** [comment]
Once we make the javascript light wallet, then a windows .exe wont matter any more.
I am starting to think we shouldn't waste time making a windows exe at all.

**Comment by stefek99** [comment]
I thought that project, in order to become more accessible should run on Windows.

I've managed to get Erlang, Rebar, get dependencies.

Now, as I try to compile the dependencies:
```
Compiling c:/Stefan/testnet/deps/jiffy/c_src/decoder.c
'cl.exe' is not recognized as an internal or external command,
operable program or batch file.
ERROR: compile failed while processing c:/Stefan/testnet/deps/jiffy: rebar_abort
```

There is an option to download standalone compiler: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/6742251-make-c-c-compiler-cl-exe-independent-of-ide

Too bad I have Visual Studio already installed - won't allow me to install standalone compiler - adding some extra packages - http://stackoverflow.com/questions/31953769/visual-studio-doesnt-have-cl-exe

> OMG. you have got to be kidding me
> Wow a 5 GB install. I wonder what C++ has been eating all these years: it's gotten fat. 

I guess we need Jiffy? https://github.com/davisp/jiffy

---

Additional question - when I try to run (extracted from `start.sh`):

> erl -pa ebin deps/*/ebin/ -eval "application:ensure_all_started(testnet), serve:pw($1), peers:add({46,101,103,165}, 8080)"

I'm getting the following error:

```
(no error logger present) error: <0.6.0>
(no error logger present) error: <0.23.0>
(no error logger present) error: <0.25.0>
(no error logger present) error: <0.18.0>
(no error logger present) error: <0.27.0>
(no error logger present) error: <0.17.0>
```

I assume it's Jiffy not being properly compiled?

I'll get `cl.exe` and update you.

-----

> we shouldn't waste time making a windows exe at all

Check analytics for your website. How many Windows users? So far it didn't cost me much...

**Comment by zack-bitcoin** [comment]
I cannot maintain any windows anything since I don't use windows.
Windows users should use spv javascript clients.

**Comment by stefek99** [comment]
SPV? https://en.wikipedia.org/wiki/SPV _(either a typo or some secret language)_

Trying to get the Windows running anyway - https://github.com/davisp/jiffy/issues/144

> I know nothing (very little) about Erlang, Rebar, Jiffy and solving dependencies on Windows

But it shouldn't be that difficult, I'm hoping that once Jiffy compiles it should be possible to run on Windows...

_(that's why I'm here so you don't have to worry about issues like this)_

**Comment by zack-bitcoin** [comment]
https://bitcoin.org/en/glossary/simplified-payment-verification

Most nodes only download the headers from blocks, and using just the headers they can verify any of the blockchain's state. Like how much money they have, and if a channel is open or not. They can make transactions and interact with the network just like a full node.

The SPV node has so little code in it, I think we can do it in javascript and have it in the browser. Then it will be compatible with everyone.

**Comment by stefek99** [comment]
SPV - of course - silly me - I should search for `spv crypto` 

I'm making attempts towards Windows anyway - it cannot be that hard :)

I was never good at solving build problems so I designed my career to work on the web... It is a matter of configuring a compiler and adding a standard library:

https://github.com/aeternity/testnet/wiki/Installing-on-Windows-(work-in-progress,-help-wanted)

_(hopefully from it will be smooth)_

I admit that most Erlang programmers are using Linux or Mac...

**Comment by zack-bitcoin** [comment]
If you want to build it on windows, I think the first step is to build an erlang release.
This is a binary with no dependencies. Erlang and Aeternity all wrapped into a single binary.

We will probably have to make a release of the code anyway for security reasons.
Otherwise the Cowboy or Jiffy developers could attack us by putting vulnerabilities into their libraries.

**Comment by stefek99** [comment]
> first step is to build an erlang release

In the instruction I've provided:

> https://www.erlang.org/downloads
> For more adventurous build it from source.

I didn't think twice, I've just downloaded the installer...

I always prefer convenience, I didn't check the `checksum` or anything :)
